markdown: rdiscount
permalink: /:title/
url: http://www.sizmoj.com
baseurl: /sizmoj.github.io
name: 细枝末节
author: sizmoj
qq: 2085526
email: pronounce_john@yahoo.com
duoshuo: biggernin
beian:
cnzz: 
weibo: 1254905274 
github: sizmoj
pygments: true
safe: true
paginate: 20
about: "杭州搬砖屌丝一枚,如果你也喜欢使用springside,欢迎加入群：85353517"
